# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_update <- function(x, z, sigma2_beta, w, y, alpha) {
    .Call(`_CumulE1_beta_update`, x, z, sigma2_beta, w, y, alpha)
}

eta_update <- function(gamma_star, corr_inv) {
    .Call(`_CumulE1_eta_update`, gamma_star, corr_inv)
}

exp_rs <- function(a, b) {
    .Call(`_CumulE1_exp_rs`, a, b)
}

gamma_star_update <- function(gamma, eta) {
    .Call(`_CumulE1_gamma_star_update`, gamma, eta)
}

gamma_update <- function(y, x, z, beta, w, gamma_old, alpha, theta, eta) {
    .Call(`_CumulE1_gamma_update`, y, x, z, beta, w, gamma_old, alpha, theta, eta)
}

half_norm_rs <- function(a, b) {
    .Call(`_CumulE1_half_norm_rs`, a, b)
}

norm_rs <- function(a, b) {
    .Call(`_CumulE1_norm_rs`, a, b)
}

phi_update <- function(phi, eta, temp_corr_info, a_phi, b_phi, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_CumulE1_phi_update`, phi, eta, temp_corr_info, a_phi, b_phi, metrop_var_phi_trans, acctot_phi_trans)
}

rnorm_trunc <- function(mu, sigma, lower, upper) {
    .Call(`_CumulE1_rnorm_trunc`, mu, sigma, lower, upper)
}

sig2_epsilon_update <- function(a_sig2_e, b_sig2_e, y, x, z, beta, alpha) {
    .Call(`_CumulE1_sig2_epsilon_update`, a_sig2_e, b_sig2_e, y, x, z, beta, alpha)
}

temporal_corr_fun <- function(p_z, phi) {
    .Call(`_CumulE1_temporal_corr_fun`, p_z, phi)
}

theta_update <- function(y, x, z, beta, gamma, sig2_theta, sig2_e) {
    .Call(`_CumulE1_theta_update`, y, x, z, beta, gamma, sig2_theta, sig2_e)
}

unif_rs <- function(a, b) {
    .Call(`_CumulE1_unif_rs`, a, b)
}

